// <auto-generated />
using System;
using HabitTracker.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTracker.Migrations
{
    [DbContext(typeof(HabitContext))]
    [Migration("20251122134735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("HabitTracker.Components.Models.Habit", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDone = false,
                            Name = "Go for a walk"
                        },
                        new
                        {
                            Id = 2,
                            IsDone = false,
                            Name = "Drink 2 liters of water"
                        },
                        new
                        {
                            Id = 3,
                            IsDone = false,
                            Name = "Walk the dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
